
--UC-1
CREATE DATABASE AddressBook;

--UC-2
CREATE TABLE ADDRESS_BOOK
(ID INT NOT NULL IDENTITY(1,1),
FIRST_NAME VARCHAR(50) NOT NULL,
LAST_NAME VARCHAR(50) NOT NULL,
ADDRESS  VARCHAR(250) NOT NULL,
CITY VARCHAR(50) NOT NULL,
STATE VARCHAR(50) NOT NULL,
ZIP CHAR(6) NOT NULL,
PhoneNO CHAR(10) NOT NULL,
EMAIL VARCHAR(80) NOT NULL,
PRIMARY KEY (ID));

--UC-3
insert into ADDRESS_BOOK (FIRST_NAME, LAST_NAME, ADDRESS, CITY, STATE, ZIP, PhoneNO, EMAIL ) VALUES
( 'Amit', 'Gajbhiye' , 'plot no.32 sugat nagar', 'Nagpur', 'Maharashtra', '440014', '9876543210', 'xyz@gmail.com' ),
( 'Meenu', 'Sahu' , 'plot no.898 Falguni putla near bridge', 'Bhopal', 'Madhya Pradesh', '440023', '9874540213', 'abc@gmail.com' ),
( 'jitu', 'Patel' , 'flat no.102  Xrbia Township', 'Surat', 'Gujrat', '440078', '9876543434', 'pqr@gmail.com' );

--UC-4
UPDATE ADDRESS_BOOK SET CITY = 'Indore' WHERE FIRST_NAME = 'Meenu';

--UC-5
DELETE FROM ADDRESS_BOOK WHERE FIRST_NAME = 'jitu';

--UC-6
SELECT * FROM ADDRESS_BOOK WHERE CITY = 'Nagpur';


--UC-7
select COUNT(STATE) AS COUNT_STATE , STATE FROM ADDRESS_BOOK GROUP BY STATE;
select COUNT(CITY) AS CITY_COUNT , CITY FROM ADDRESS_BOOK GROUP BY CITY;

--UC-8
SELECT * FROM ADDRESS_BOOK WHERE CITY= 'Pune' ORDER BY FIRST_NAME;


--UC-9
ALTER TABLE ADDRESS_BOOK ADD Type VARCHAR(20); --added new column "Type"

UPDATE ADDRESS_BOOK SET Type ='Family' where FIRST_NAME = 'Amit'; ---- inserted values in Type column
UPDATE ADDRESS_BOOK SET Type ='Lawyer' where FIRST_NAME = 'Meenu'; ---- inserted values in Type column


--UC-10
SELECT COUNT(FIRST_NAME) as Countofperson, Type FROM ADDRESS_BOOK GROUP BY Type;



--UC-11

insert into ADDRESS_BOOK (FIRST_NAME, LAST_NAME, ADDRESS, CITY, STATE, ZIP, PhoneNO, EMAIL, Type) VALUES  
( 'Isha', 'singh' , 'plot no.93 sumedh nagar', 'Pune', 'Maharashtra', '440015', '9876543718', 'defg@gmail.com', 'Family'),
( 'Vidhi', 'Patel' , 'plot no.78 kushi nagar', 'Patna', 'Bihar', '440088', '9876543718', 'defg@gmail.com', 'Friends');


--UC-12

--///new table 
CREATE TABLE PERSON_ADDRESS(
PERSON_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
FIRSTNAME VARCHAR(30) NOT NULL,
LASTNAME VARCHAR(30) NOT NULL,
ADDRESS VARCHAR(200) NOT NULL,
CITY VARCHAR(25) NOT NULL,
STATE VARCHAR(25) NOT NULL,
ZIPCODE CHAR(6) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
TYPE_ID INT NOT NULL);

INSERT INTO PERSON_ADDRESS VALUES('LEENU','GAJBHIYE','KARVE NAGAR','PUNE','MAHARASHTRA',474747,'asdf@gmail.com',1)
INSERT INTO PERSON_ADDRESS VALUES('CHEENU','PATEL','NAGSEN','MUMBAI','MAHARASHTRA',423456,'wdes@gmail.com',2)
INSERT INTO PERSON_ADDRESS VALUES('MEENU','SONI','SUGAT NAGAR','SARNI','MADHYA PRADESH',433333,'qsea@gmail.com',1)
INSERT INTO PERSON_ADDRESS VALUES('TINU','SINGH','CHICHOLI','PATNA','BIHAR',404040,'idgd@gmail.com',1)


SELECT * FROM PERSON_ADDRESS;

--//new table
CREATE TABLE CONTACT_TYPE
(TYPE_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
TYPE_NAME VARCHAR(25) NOT NULL);

INSERT INTO CONTACT_TYPE VALUES('FAMILY'),('FRIENDS'),('LAWYER')
SELECT * FROM CONTACT_TYPE


--////new table 
CREATE TABLE PERSON_PHONE
(CONTACT_ID INT NOT NULL,
FIRST_NAME VARCHAR(25) NOT NULL,
PHONE_1 CHAR(10) NOT NULL,
PHONE_2 CHAR(10) NULL);

INSERT INTO PERSON_PHONE VALUES(101,'AMIT',0987654321,9876234567)
INSERT INTO PERSON_PHONE VALUES(102,'SUMIT',9087654321,9900334422)
INSERT INTO PERSON_PHONE VALUES(103,'ROHIT',9807654321,9998887770)
INSERT INTO PERSON_PHONE VALUES(104,'SURBHI',7676767676,8452525244)

SELECT * FROM PERSON_PHONE


ALTER TABLE PERSON_ADDRESS ADD CONSTRAINT FK_CONTACT_TYPE FOREIGN KEY(TYPE_ID) REFERENCES CONTACT_TYPE(TYPE_ID) ON DELETE CASCADE ON UPDATE CASCADE
ALTER TABLE PERSON_PHONE ADD CONSTRAINT FK_PERSON_PHONE FOREIGN KEY(PERSON_ID) REFERENCES PERSON_ADDRESS(PERSON_ID) ON DELETE CASCADE ON UPDATE CASCADE
ALTER TABLE PERSON_PHONE ADD PERSON_ID INT 



--UC-13

SELECT * FROM PERSON_ADDRESS WHERE CITY = 'PUNE';
SELECT * FROM PERSON_ADDRESS WHERE STATE = 'SARNI';

SELECT CITY, COUNT(CITY) AS CONTACT_ADDRESS FROM ADDRESS_BOOK GROUP BY CITY;
SELECT STATE, COUNT(STATE) AS CONTACT_ADDRESS FROM ADDRESS_BOOK GROUP BY STATE;

SELECT * FROM PERSON_ADDRESS WHERE CITY = 'surat' ORDER BY FIRSTNAME;

SELECT TYPE_NAME,COUNT(TYPE_NAME) FROM CONTACT_TYPE CT INNER JOIN PERSON_ADDRESS CA ON CT.TYPE_ID = CA.TYPE_ID GROUP BY TYPE_NAME


